name: Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - README.md
      - .gitignore
      - .gitpod.yml
      - LICENSE
  pull_request:
    branches: [ main ]
    paths-ignore:
      - README.md
      - .gitignore
      - .gitpod.yml
      - LICENSE

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]
    name: Build with Java ${{ matrix.Java }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: maven
      - name: maven-settings
        uses: s4u/maven-settings-action@v3.1.0
        with:
          servers: '[{"id": "github", "username": "${{ secrets.MAVEN_REGISTRY_USERNAME }}", "password": "${{ secrets.MAVEN_REGISTRY_TOKEN }}"}]'
          githubServer: false
      - name: Maven build
        run: mvn package
