name: E2E
on:
  push:
    branches: [ main ]
    paths-ignore:
      - README.md
      - .gitignore
      - .gitpod.yml
      - LICENSE
  pull_request:
    branches: [ main ]
    paths-ignore:
      - README.md
      - .gitignore
      - .gitpod.yml
      - LICENSE
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn spring-boot:run -Dskip.frontend.build=false &
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install Playwright
      run: npm install playwright
    - name: Run Playwright tests
      run: npx playwright test
      env:
        CI: true

